// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using ProspAI_Sprint3.Data;

#nullable disable

namespace ProspAI_Sprint3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Funcionario", b =>
                {
                    b.Property<int>("Id_fun")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_fun"));

                    b.Property<DateTime>("Data_admissao")
                        .HasColumnType("date")
                        .HasColumnName("dt_adm");

                    b.Property<string>("Email_fun")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar2(50)")
                        .HasColumnName("ds_email");

                    b.Property<string>("Nome_fun")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar2(30)")
                        .HasColumnName("nm_fun");

                    b.Property<string>("Senha_fun")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar2(100)")
                        .HasColumnName("ds_senha");

                    b.HasKey("Id_fun");

                    b.ToTable("TB_Funcionario_Sprint3");
                });

            modelBuilder.Entity("ProspAI_Sprint3.Models.Desempenho", b =>
                {
                    b.Property<int>("Id_desem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_desem"));

                    b.Property<int>("Id_fun")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Mes_desem")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar2(15)")
                        .HasColumnName("ds_mes");

                    b.Property<byte>("Reclamacoes_resp")
                        .HasColumnType("number(3)")
                        .HasColumnName("nr_reclama");

                    b.Property<byte>("Reclamacoes_solu")
                        .HasColumnType("number(3)")
                        .HasColumnName("nr_reclama_solu");

                    b.HasKey("Id_desem");

                    b.HasIndex("Id_fun");

                    b.ToTable("TB_Desempenho_Sprint3");
                });

            modelBuilder.Entity("ProspAI_Sprint3.Models.Reclamacao", b =>
                {
                    b.Property<int>("Id_recla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_recla"));

                    b.Property<string>("Assunto_recla")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar2(100)")
                        .HasColumnName("as_recla");

                    b.Property<DateTime>("Dt_recla")
                        .HasColumnType("date")
                        .HasColumnName("dt_recla");

                    b.Property<int>("Id_fun")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nm_clie")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar2(30)")
                        .HasColumnName("nm_clie");

                    b.Property<string>("Origem_recla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar2(20)")
                        .HasColumnName("og_recla");

                    b.Property<string>("Solucionada_recla")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)")
                        .HasColumnName("st_solu");

                    b.HasKey("Id_recla");

                    b.HasIndex("Id_fun");

                    b.ToTable("TB_Reclamacao_Sprint3");
                });

            modelBuilder.Entity("ProspAI_Sprint3.Models.Desempenho", b =>
                {
                    b.HasOne("Funcionario", "Funcionario")
                        .WithMany("Desempenhos")
                        .HasForeignKey("Id_fun")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("ProspAI_Sprint3.Models.Reclamacao", b =>
                {
                    b.HasOne("Funcionario", "Funcionario")
                        .WithMany("Reclamacoes")
                        .HasForeignKey("Id_fun")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("Funcionario", b =>
                {
                    b.Navigation("Desempenhos");

                    b.Navigation("Reclamacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
